# Copyright (c) 2023 Hartmut Kaiser
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (Release)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: stellargroup/build_env:latest

    steps:
    - uses: actions/checkout@v3
      with:
          repository: ct-clmsn/chplx.git
          fetch-depth: 1
    - name: Install dependencies
      shell: bash
      run: |
          mkdir -p /tmp/hpx
          cd /tmp/hpx
          git clone \
              --branch master \
              --single-branch \
              --depth 1 \
              https://github.com/STEllAR-GROUP/hpx.git
          mkdir -p build
          cd build
          cmake \
              ../hpx \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DHPX_WITH_UNITY_BUILD=ON \
              -DHPX_WITH_MALLOC=system \
              -DHPX_WITH_EXAMPLES=OFF \
              -DHPX_WITH_TESTS=OFF
          ninja install
    - name: Configure
      shell: bash
      run: |
          cmake \
              ./library \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
    - name: Test
      shell: bash
      run: |
          cd build
          ctest --output-on-failure